// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Крипто_студия
{

    internal class get_ticker
    {

        [JsonProperty("asks")]
        public object[][] Asks { get; set; }

        [JsonProperty("bids")]
        public object[][] Bids { get; set; }

        [JsonProperty("isFrozen")]
        public string IsFrozen { get; set; }

        [JsonProperty("seq")]
        public int Seq { get; set; }
    }

}
